name: md_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  image_picker: ^1.0.4
  google_mlkit_barcode_scanning: ^0.14.1
  excel: ^2.0.7
  intl: ^0.19.0
  flutter_date_pickers: ^0.4.0
  mobile_scanner: ^5.2.1
  dropdown_search: ^5.0.6
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.4
  image_gallery_saver_plus: ^4.0.1 


flutter_native_splash:
  color: "#ffffff"
  image: "assets/ic_launcher.png"
  android: true
  ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ 
    - assets/ic_launcher.png
    - assets/export_all_tables_23-06-2025_1.xlsx
